<?php
/**
 * @file
 * Code for the CU Degree Programs feature.
 */

include_once 'cu_degree_programs.features.inc';

function cu_degree_programs_preprocess_node(&$variables) {
  if ($variables['type'] == 'degree_program') {
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__' . $variables['view_mode'];
  }
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got node--degree-program.tpl.php in our module
 * directory.
 */
function cu_degree_programs_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_degree_programs');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'node', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}

/**
 * Implements hook_page_alter().
 */
function cu_degree_programs_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'cu_degree_programs') . '/css/cu-degree-programs.css');
  if (current_path() == 'academics/programs') {
    drupal_add_js(drupal_get_path('module','cu_degree_programs') .'/js/cu-degree-programs.js');
  }
}