<?php
/**
 * @file
 * Code for the CU Homepage Policy feature.
 */

include_once 'cu_homepage_policy.features.inc';

/**
 * Implements hook_node_view().
 */
function cu_homepage_policy_node_view($node, $view_mode) {
  switch($node->type) {
    case 'policy':
      // Direct 'Policy' nodes to external url if provided.
      if ($view_mode == 'full' && !empty($node->field_policy_external_url[LANGUAGE_NONE][0]['url'])) {
        drupal_goto($node->field_policy_external_url[LANGUAGE_NONE][0]['url']);
      } elseif ($view_mode == 'full' && !empty($node->field_policy_file[LANGUAGE_NONE][0]['uri'])) {
        drupal_goto(file_create_url($node->field_policy_file[LANGUAGE_NONE][0]['uri']));
      }
      break;
  }
}
