<?php

/**
 * Delete legacy fields from person node type:
 * field_extra, field_person_interests,field_person_bio.
 */
function cu_homepage_people_update_7001() {
  // Get fields
  $fields = array(
    'field_extra',
    'field_person_interests',
    'field_person_bio',
  );
  // Delete fields from person nodes
  foreach ($fields as $field) {
    if ($instance = field_info_instance('node', $field, 'person')) {
      field_delete_instance($instance);
    }
  }
}
