<?php

/**
 * Implements hook_menu().
 */
function cu_404_menu() {
  $items['fourohfour'] = array(
    'title' => 'Page Not Found',
    'page callback' => 'cu_404_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Page callback for 'fourohfour'.
 */
function cu_404_page() {
  $content = array();

  $request_uri = request_uri();

  // Convert the uri to a lower case string.
  $lowered_uri = drupal_strtolower($request_uri);

  // If there was a caps char anywhere in the URL, forward to lowered path.
  if ($request_uri != $lowered_uri) {
    // Can't use drupal_goto - it doesn't change the $_SERVER variable.
    // It preserves it - the browser gets stuck in an infinite loop.
    // Also cannot simply use header() either. While this works locally and
    // logged in to WWWNG, anon users were never being directed to the lowered
    // url, possibly due to the fact that the request wasn't making its way
    // back out to the F5.
    $options['absolute'] = TRUE;
    $lowered_uri = ltrim($lowered_uri, '/');
    $url = url($lowered_uri, $options);
    drupal_add_js('window.location.replace("' . $url . '");', 'inline');
  }

  // There was nothing wrong with the uri, display the 404 error image
  $content['image'] = array(
    '#theme' => 'image',
    '#path' => drupal_get_path('module', 'cu_404') . '/content/404.jpg',
    '#alt' => t('The page you are looking for appears to have been moved, deleted, or does not exist.'),
  );

  return $content;
}
